# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73dd79223bcc963fd6807051843c002de7e6cc4ac8734dd957a174de0633a998a6620f6c616c860408236d8ce846eee8b7239d013ddf74b11ad6a61437810d21

test:
  secret_key_base: c4565ac5d6b06cb8b7df92b377640478428358913ca226ab7d373a6b7457156cf5de6b50a2c0003ec771f4cc30495675f50b42d5fe28c4605228b8c105f94927

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
